name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libavif-dev libjpeg-turbo8-dev libwebp-dev libspng-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install libavif libjpeg-turbo webp libspng

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git $env:USERPROFILE\vcpkg
          & $env:USERPROFILE\vcpkg\bootstrap-vcpkg.bat
          & $env:USERPROFILE\vcpkg\vcpkg.exe install libavif:x64-windows libjpeg-turbo:x64-windows libwebp:x64-windows libspng:x64-windows
          "CPATH=$env:USERPROFILE\vcpkg\installed\x64-windows\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "LIB=$env:USERPROFILE\vcpkg\installed\x64-windows\lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "PATH=$env:USERPROFILE\vcpkg\installed\x64-windows\bin;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build
        run: zig build -Doptimize=ReleaseFast

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oavif-${{ runner.os }}
          path: zig-out/bin/
          if-no-files-found: error
